site_name: WoltLab Suite Documentation
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/default.favicon.ico
  palette:
    primary: teal
  font: false
  features:
    - navigation.tracking
copyright: Copyright Â© 2020 WoltLab GmbH
site_url: https://docs.woltlab.com/
repo_url: https://github.com/WoltLab/docs.woltlab.com/
edit_uri: edit/6.0/docs/

nav:
  - 'Getting Started': 'getting-started.md'

  - 'PHP API':
      - 'Pages': 'php/pages.md'
      - 'Database Objects': 'php/database-objects.md'
      - 'Database Access': 'php/database-access.md'
      - 'Exceptions': 'php/exceptions.md'
      - 'API':
          - 'Caches':
              - 'Overview': 'php/api/caches.md'
              - 'Persistent Caches': 'php/api/caches_persistent-caches.md'
              - 'Runtime Caches': 'php/api/caches_runtime-caches.md'
          - 'Comments': 'php/api/comments.md'
          - 'Cronjobs': 'php/api/cronjobs.md'
          - 'Events': 'php/api/events.md'
          - 'Form Builder':
              - 'Overview': 'php/api/form_builder/overview.md'
              - 'Structure': 'php/api/form_builder/structure.md'
              - 'Fields': 'php/api/form_builder/form_fields.md'
              - 'Validation and Data': 'php/api/form_builder/validation_data.md'
              - 'Dependencies': 'php/api/form_builder/dependencies.md'
          - 'Package Installation Plugins': 'php/api/package_installation_plugins.md'
          - 'User Activity Points': 'php/api/user_activity_points.md'
          - 'User Notifications': 'php/api/user_notifications.md'
          - 'Sitemaps': 'php/api/sitemaps.md'
      - 'Code Style': 'php/code-style.md'
      - 'Apps': 'php/apps.md'
      - 'GDPR': 'php/gdpr.md'

  - 'Languages, Templates & CSS':
      - 'Languages': 'view/languages.md'
      - 'Templates': 'view/templates.md'
      - 'Template Plugins': 'view/template-plugins.md'
      - 'CSS': 'view/css.md'

  - 'TypeScript and JavaScript API':
      - 'General Usage': 'javascript/general-usage.md'
      - 'TypeScript': 'javascript/typescript.md'
      - 'Components':
          - 'Confirmation': 'javascript/components_confirmation.md'
          - 'Dialog': 'javascript/components_dialog.md'
          - 'Google Maps': 'javascript/components_google_maps.md'
          - 'Pagination': 'javascript/components_pagination.md'
      - 'New API':
          - 'Writing a module': 'javascript/new-api_writing-a-module.md'
          - 'Core Functions': 'javascript/new-api_core.md'
          - 'DOM': 'javascript/new-api_dom.md'
          - 'Event Handling': 'javascript/new-api_events.md'
          - 'Ajax': 'javascript/new-api_ajax.md'
          - 'Dialogs': 'javascript/new-api_dialogs.md'
          - 'Browser and Screen Sizes': 'javascript/new-api_browser.md'
          - 'User Interface': 'javascript/new-api_ui.md'
      - 'Legacy API': 'javascript/legacy-api.md'
      - 'Code Snippets': 'javascript/code-snippets.md'

  - 'Package Components':
      - 'package.xml': 'package/package-xml.md'
      - 'PIPs':
          - 'Overview': 'package/pip.md'
          - 'aclOption': 'package/pip/acl-option.md'
          - 'acpMenu': 'package/pip/acp-menu.md'
          - 'acpSearchProvider': 'package/pip/acp-search-provider.md'
          - 'acpTemplate': 'package/pip/acp-template.md'
          - 'acpTemplateDelete': 'package/pip/acp-template-delete.md'
          - 'bbcode': 'package/pip/bbcode.md'
          - 'box': 'package/pip/box.md'
          - 'clipboardAction': 'package/pip/clipboard-action.md'
          - 'coreObject': 'package/pip/core-object.md'
          - 'cronjob': 'package/pip/cronjob.md'
          - 'database': 'package/pip/database.md'
          - 'eventListener': 'package/pip/event-listener.md'
          - 'file': 'package/pip/file.md'
          - 'fileDelete': 'package/pip/file-delete.md'
          - 'language': 'package/pip/language.md'
          - 'mediaProvider': 'package/pip/media-provider.md'
          - 'menu': 'package/pip/menu.md'
          - 'menuItem': 'package/pip/menu-item.md'
          - 'objectType': 'package/pip/object-type.md'
          - 'objectTypeDefinition': 'package/pip/object-type-definition.md'
          - 'option': 'package/pip/option.md'
          - 'page': 'package/pip/page.md'
          - 'pip': 'package/pip/pip.md'
          - 'script': 'package/pip/script.md'
          - 'smiley': 'package/pip/smiley.md'
          - 'sql': 'package/pip/sql.md'
          - 'style': 'package/pip/style.md'
          - 'template': 'package/pip/template.md'
          - 'templateDelete': 'package/pip/template-delete.md'
          - 'templateListener': 'package/pip/template-listener.md'
          - 'userGroupOption': 'package/pip/user-group-option.md'
          - 'userMenu': 'package/pip/user-menu.md'
          - 'userNotificationEvent': 'package/pip/user-notification-event.md'
          - 'userOption': 'package/pip/user-option.md'
          - 'userProfileMenu': 'package/pip/user-profile-menu.md'
      - 'Database PHP API': 'package/database-php-api.md'

  - 'Migration':
      - 'From WoltLab Suite 5.5':
          - 'PHP API': 'migration/wsc55/php.md'
          - 'TypeScript and JavaScript': 'migration/wsc55/javascript.md'
          - 'Templates': 'migration/wsc55/templates.md'
          - 'Icons': 'migration/wsc55/icons.md'
          - 'Dialogs': 'migration/wsc55/dialogs.md'
          - 'Third Party Libraries': 'migration/wsc55/libraries.md'
          - 'Deprecations and Removals': 'migration/wsc55/deprecations_removals.md'
      - 'From WoltLab Suite 5.4':
          - 'PHP API': 'migration/wsc54/php.md'
          - 'TypeScript and JavaScript': 'migration/wsc54/javascript.md'
          - 'Templates': 'migration/wsc54/templates.md'
          - 'Third Party Libraries': 'migration/wsc54/libraries.md'
          - 'Deprecations and Removals': 'migration/wsc54/deprecations_removals.md'
      - 'From WoltLab Suite 5.3':
          - 'PHP API': 'migration/wsc53/php.md'
          - 'Session Handling and Authentication': 'migration/wsc53/session.md'
          - 'TypeScript and JavaScript': 'migration/wsc53/javascript.md'
          - 'Templates': 'migration/wsc53/templates.md'
          - 'Third Party Libraries': 'migration/wsc53/libraries.md'
      - 'From WoltLab Suite 5.2':
          - 'PHP API': 'migration/wsc52/php.md'
          - 'Templates and Languages': 'migration/wsc52/templates.md'
          - 'Third Party Libraries': 'migration/wsc52/libraries.md'
      - 'From WoltLab Suite 3.1':
          - 'PHP API': 'migration/wsc31/php.md'
      - 'From WoltLab Suite 3.0':
          - 'PHP API': 'migration/wsc30/php.md'
          - 'JavaScript API': 'migration/wsc30/javascript.md'
          - 'Templates': 'migration/wsc30/templates.md'
          - 'CSS': 'migration/wsc30/css.md'
          - 'Package Components': 'migration/wsc30/package.md'
      - 'From WCF 2.1':
          - 'PHP API': 'migration/wcf21/php.md'
          - 'Templates': 'migration/wcf21/templates.md'
          - 'CSS': 'migration/wcf21/css.md'
          - 'Package Components': 'migration/wcf21/package.md'

  - 'Tutorials':
      - 'Tutorial Series':
          - 'Overview': 'tutorial/series/overview.md'
          - 'Part 1': 'tutorial/series/part_1.md'
          - 'Part 2': 'tutorial/series/part_2.md'
          - 'Part 3': 'tutorial/series/part_3.md'
          - 'Part 4': 'tutorial/series/part_4.md'
          - 'Part 5': 'tutorial/series/part_5.md'
          - 'Part 6': 'tutorial/series/part_6.md'

plugins:
  - git-revision-date
  - search
  - macros:
      j2_comment_start_string: '{jinja#'
      j2_variable_start_string: '{jinja{'

markdown_extensions:
  - toc:
      permalink: '#'
      toc_depth: 4
  - admonition
  - abbr
  - pymdownx.highlight:
      linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'snippets/'

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
  social: true
